*;
* IMPUTE VARIABLE: domestic_gross;
*;
format IMP_domestic_gross BEST12.0;
label IMP_domestic_gross = 'Imputed domestic_gross';
IMP_domestic_gross = domestic_gross;
if missing(IMP_domestic_gross) then do;
****************************************************************;
****** DECISION TREE SCORING CODE ******;
****************************************************************;
****** LENGTHS OF NEW CHARACTER VARIABLES ******;
LENGTH _WARN_ $ 4;
****** LABELS FOR NEW VARIABLES ******;
label P_domestic_gross = 'Predicted: domestic_gross';
label _WARN_ = 'Warnings';
****** TEMPORARY VARIABLES FOR FORMATTED VALUES ******;
LENGTH _ARBFMT_12 $ 12;
DROP _ARBFMT_12;
_ARBFMT_12 = ' ';
/* Initialize to avoid warning. */
****** ASSIGN OBSERVATION TO NODE ******;
DROP _BRANCH_;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 468025168.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
468025168.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 312833912 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 312833912 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 54057977 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 54057977 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 180913523.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
180913523.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 1320503916.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1320503916.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 917274092 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 917274092 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 673023912.777777;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 102958726 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
102958726 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 389.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 389.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 389.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 389.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 1027018999.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
1027018999.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 620044632.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 620044632.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 146848572 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 146848572 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 430702154.3;
END;
ELSE DO;
P_domestic_gross = 344622521.352941;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 960234546 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
960234546 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 681557973.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 681557973.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 97614055 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 97614055 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 338625252.066666;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 66992344.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
66992344.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 639467409.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 639467409.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Fantasy ) THEN DO;
_ARBFMT_12 = PUT( genre_Fantasy , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 247683801.103448;
END;
ELSE DO;
P_domestic_gross = 187492981.285714;
END;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 72732690 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
72732690 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 36937749 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 36937749 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 12629256 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 12629256 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 24957971.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
24957971.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 240747739.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 240747739.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 154466191 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 154466191 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 41274258 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
41274258 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 375.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 375.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 375.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 375.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 54986379.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
54986379.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF 108081801 <= foreign_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF foreign_gross < 108081801 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets ) THEN DO;
IF 16.5 <= markets THEN DO;
_BRANCH_ = 1;
END;
ELSE IF markets < 16.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 179550774.090909;
END;
ELSE DO;
P_domestic_gross = 138663438.142857;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 172553734 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
172553734 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 70072002 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 70072002 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets ) THEN DO;
IF markets < 37.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 37.5 <= markets THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 29943435.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
29943435.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 132593449.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 132593449.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Horror ) THEN DO;
_ARBFMT_12 = PUT( genre_Horror , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_domestic_gross = 70616262.9333333;
END;
ELSE DO;
P_domestic_gross = 95058224.9090909;
END;
END;
ELSE DO;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( NR , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF 23 <= ss_count THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_count < 23 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF 23 <= tomatometer_count THEN DO;
_BRANCH_ = 1;
END;
ELSE IF tomatometer_count < 23 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 152152287.25;
END;
ELSE DO;
P_domestic_gross = 109265148.986301;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 151939021.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
151939021.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 97373086 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 97373086 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 21113376.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 21113376.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 104507959.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
104507959.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 177549968 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 177549968 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets_missing ) THEN DO;
_ARBFMT_12 = PUT( markets_missing , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 225625620 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
225625620 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 116055.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 116055.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 103884247.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 103884247.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 175321620.8;
END;
ELSE DO;
P_domestic_gross = 94352207.0714285;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(markets ) AND
markets < 18 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(markets ) AND
18 <= markets THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 94294.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 94294.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 10 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 10 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_domestic_gross = 774495.916666666;
END;
ELSE DO;
P_domestic_gross = 68663533.9113924;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 43130631 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
43130631 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 85221279.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 85221279.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 20630703 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 20630703 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 89664025.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
89664025.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 20299752.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 20299752.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Romance ) THEN DO;
_ARBFMT_12 = PUT( genre_Romance , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 77832245.1071428;
END;
ELSE DO;
P_domestic_gross = 54124280.2619047;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 14220699 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
14220699 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 118950007 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 118950007 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(PG ) THEN DO;
_ARBFMT_12 = PUT( PG , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 54540041.2068965;
END;
ELSE DO;
P_domestic_gross = 29625172.9368421;
END;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 24937431 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
24937431 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 5995359.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 5995359.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 14501592 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 14501592 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 7928287 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
7928287 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 51131395.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 51131395.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF 9549110.5 <= foreign_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF foreign_gross < 9549110.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 15859256 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
15859256 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 71981442 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 71981442 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 48851999.2631579;
END;
ELSE DO;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( markets_missing , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF 432891 <= foreign_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF foreign_gross < 432891 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF 5.5 <= tomatometer_count THEN DO;
_BRANCH_ = 1;
END;
ELSE IF tomatometer_count < 5.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 41588318.7619047;
END;
ELSE DO;
P_domestic_gross = 29890827.6083333;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 14741067.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
14741067.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets_missing ) THEN DO;
_ARBFMT_12 = PUT( markets_missing , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 26386324 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 26386324 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 46101967.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
46101967.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 251.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 251.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 251.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 251.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 50527721.8461538;
END;
ELSE DO;
P_domestic_gross = 24962357;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 132009 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
132009 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(NR ) THEN DO;
_ARBFMT_12 = PUT( NR , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 28.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 28.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_domestic_gross = 2428294.9245283;
END;
ELSE DO;
P_domestic_gross = 16107553.9537037;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 2013437.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
2013437.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 23860951.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 23860951.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 14334391 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
14334391 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 3381200.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 3381200.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 2919346 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 2919346 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 10098782.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
10098782.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 3858341.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 3858341.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 4151226.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 4151226.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 9964251.09375;
END;
ELSE DO;
P_domestic_gross = 6595138.66071428;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 6906187.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
6906187.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 24100256.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 24100256.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 9794886.12903225;
END;
ELSE DO;
P_domestic_gross = 16290576.1486486;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 70266.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
70266.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 148.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 148.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 148.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 148.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 13057847.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
13057847.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 9062010 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 9062010 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 266.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 266.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 8383152.875;
END;
ELSE DO;
P_domestic_gross = 2246315.91044776;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 5771245 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
5771245 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 5836050 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 5836050 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 221.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 221.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 1431212.17326732;
END;
ELSE DO;
P_domestic_gross = 130599.141993957;
END;
END;
END;
END;
END;
END;
****************************************************************;
****** END OF DECISION TREE SCORING CODE ******;
****************************************************************;
*;
* ASSIGN VALUE TO: domestic_gross;
*;
IMP_domestic_gross = P_DOMESTIC_GROSS;
END;
