*;
* IMPUTE VARIABLE: total_gross;
*;
format IMP_total_gross BEST12.0;
label IMP_total_gross = 'Imputed total_gross';
IMP_total_gross = total_gross;
if missing(IMP_total_gross) then do;
****************************************************************;
****** DECISION TREE SCORING CODE ******;
****************************************************************;
****** LENGTHS OF NEW CHARACTER VARIABLES ******;
LENGTH _WARN_ $ 4;
****** LABELS FOR NEW VARIABLES ******;
label P_total_gross = 'Predicted: total_gross';
label _WARN_ = 'Warnings';
****** TEMPORARY VARIABLES FOR FORMATTED VALUES ******;
LENGTH _ARBFMT_12 $ 12;
DROP _ARBFMT_12;
_ARBFMT_12 = ' ';
/* Initialize to avoid warning. */
****** ASSIGN OBSERVATION TO NODE ******;
DROP _BRANCH_;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 209769806 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
209769806 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 36183476 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 36183476 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 180106951.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 180106951.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 497674731.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
497674731.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 258063773.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 258063773.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 70742152 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 70742152 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 379458207.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
379458207.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 144546122 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 144546122 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 700722477.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 700722477.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 1322114001.6;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 599952829 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
599952829 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 87528787.5 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 87528787.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF 320 <= ss_count THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_count < 320 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_total_gross = 852226851.444444;
END;
ELSE DO;
P_total_gross = 976231703.5;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 362415006 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
362415006 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 56434517.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 56434517.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 203768682.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 203768682.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 307818626.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
307818626.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 94081561 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 94081561 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets ) THEN DO;
IF markets < 68 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 68 <= markets THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 790399557.666666;
END;
ELSE DO;
P_total_gross = 619959051.266666;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 126919325 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
126919325 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.71408663799968 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.71408663799968 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.40799062412157 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.40799062412157 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 479404609.894736;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 264850948 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
264850948 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 251.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 251.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 251.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 251.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 390861893.5;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 93440194 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
93440194 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 15251053 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 15251053 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF 251653801 <= foreign_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF foreign_gross < 251653801 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_total_gross = 270821827.8;
END;
ELSE DO;
P_total_gross = 351981329;
END;
END;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 49625565.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
49625565.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 50111889 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 50111889 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 14564133 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 14564133 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 119859607.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
119859607.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 36836865 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 36836865 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 131692.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 131692.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 146538996.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
146538996.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 26983631 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 26983631 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF 100.5 <= runtime THEN DO;
_BRANCH_ = 1;
END;
ELSE IF runtime < 100.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 349289628.461538;
END;
ELSE DO;
P_total_gross = 257175918.133333;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 110604191 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
110604191 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 79521 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 79521 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF 137715.5 <= domestic_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_gross < 137715.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 59911710.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
59911710.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 20832558 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 20832558 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 43440 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 43440 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 179003230 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
179003230 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF 143185.5 <= domestic_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_gross < 143185.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 41413.5 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 41413.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 211993829.4;
END;
ELSE DO;
P_total_gross = 170157033.444444;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 148015012.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
148015012.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 27361133 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 27361133 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF ss_std < 0.49667831107278 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.49667831107278 <= ss_std THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 265515111.4;
END;
ELSE DO;
P_total_gross = 209790942.933333;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 50364477.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
50364477.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 17289877 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 17289877 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF 109.5 <= runtime THEN DO;
_BRANCH_ = 1;
END;
ELSE IF runtime < 109.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 82487467 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
82487467 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 28345976.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 28345976.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.83035714285714 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.83035714285714 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 170684172.285714;
END;
ELSE DO;
P_total_gross = 135324807.233333;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 87671119.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
87671119.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF 1559515 <= domestic_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_gross < 1559515 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 250.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 250.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 119133702.1;
END;
ELSE DO;
P_total_gross = 91917392.8857143;
END;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 24507662.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
24507662.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 7146518 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 7146518 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 21134582 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 21134582 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 61987615 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
61987615 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 20481833.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 20481833.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 94555 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 94555 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 93581984.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
93581984.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Action ) THEN DO;
_ARBFMT_12 = PUT( genre_Action , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Adventure ) THEN DO;
_ARBFMT_12 = PUT( genre_Adventure , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 135558336.7;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 7677929 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
7677929 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets_missing ) THEN DO;
_ARBFMT_12 = PUT( markets_missing , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 12466810 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 12466810 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_total_gross = 78972750.875;
END;
ELSE DO;
P_total_gross = 107754154.428571;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 28068603 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
28068603 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 323 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 323 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 323 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 323 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 38161218 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
38161218 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 32741827 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 32741827 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_ThrillMysSusp ) THEN DO;
_ARBFMT_12 = PUT( genre_ThrillMysSusp , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_total_gross = 65987026.2666666;
END;
ELSE DO;
P_total_gross = 86848219.1923077;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 40782953 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
40782953 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 12963193.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 12963193.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 122085 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 122085 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 58638239.3571428;
END;
ELSE DO;
P_total_gross = 43210418.75;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 8070011 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
8070011 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 6301512.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 6301512.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 16376670 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 16376670 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 19876379.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
19876379.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 8288564 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 8288564 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_AnimationManga ) THEN DO;
_ARBFMT_12 = PUT( genre_AnimationManga , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 35775187 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
35775187 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 23689 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 23689 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Fantasy ) THEN DO;
_ARBFMT_12 = PUT( genre_Fantasy , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 51130956.8461538;
END;
ELSE DO;
P_total_gross = 33646497.3191489;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 8026918 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
8026918 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 82304 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 82304 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 137 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 137 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 28584459.7826087;
END;
ELSE DO;
P_total_gross = 14158466.5479452;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 5460935.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
5460935.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 2213461 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 2213461 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 275.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 275.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 14497930.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
14497930.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 5558268 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 5558268 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF 5.5 <= ss_count THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_count < 5.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 20760200.4054054;
END;
ELSE DO;
P_total_gross = 11569474.4714285;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 2065124.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
2065124.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 175.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 175.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 175.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 175.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_total_gross = 5093600.93969849;
END;
ELSE DO;
P_total_gross = 542348.006902502;
END;
END;
END;
END;
END;
END;
****************************************************************;
****** END OF DECISION TREE SCORING CODE ******;
****************************************************************;
*;
* ASSIGN VALUE TO: total_gross;
*;
IMP_total_gross = P_TOTAL_GROSS;
END;
