*;
* IMPUTE VARIABLE: ss_count;
*;
format IMP_ss_count BEST12.0;
label IMP_ss_count = 'Imputed ss_count';
IMP_ss_count = ss_count;
if missing(IMP_ss_count) then do;
****************************************************************;
****** DECISION TREE SCORING CODE ******;
****************************************************************;
****** LENGTHS OF NEW CHARACTER VARIABLES ******;
LENGTH _WARN_ $ 4;
****** LABELS FOR NEW VARIABLES ******;
label P_ss_count = 'Predicted: ss_count';
label _WARN_ = 'Warnings';
****** TEMPORARY VARIABLES FOR FORMATTED VALUES ******;
LENGTH _ARBFMT_12 $ 12;
DROP _ARBFMT_12;
_ARBFMT_12 = ' ';
/* Initialize to avoid warning. */
****** ASSIGN OBSERVATION TO NODE ******;
DROP _BRANCH_;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 124.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
124.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 13550 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 13550 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 241.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
241.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 85537330 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 85537330 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 208674927 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 208674927 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 336 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
336 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 185116167 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 185116167 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 87805861 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 87805861 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 408 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
408 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 150729016.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 150729016.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 579532717 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 579532717 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 442.846153846153;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 371.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
371.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Fantasy ) THEN DO;
_ARBFMT_12 = PUT( genre_Fantasy , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Sci_fi ) THEN DO;
_ARBFMT_12 = PUT( genre_Sci_fi , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 392 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
392 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 118967784 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 118967784 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 278820184 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 278820184 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 401.4;
END;
ELSE DO;
P_ss_count = 381.444444444444;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 352 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
352 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 167910000.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 167910000.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 23359300.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 23359300.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 342.5;
END;
ELSE DO;
P_ss_count = 363.222222222222;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 291 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
291 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 532014771 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 532014771 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 764066655.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 764066655.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 309.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
309.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 177976273.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 177976273.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 32405992 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 32405992 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 320.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
320.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF 59248 <= user_rating_count THEN DO;
_BRANCH_ = 1;
END;
ELSE IF user_rating_count < 59248 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF 312111059 <= domestic_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_gross < 312111059 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 328.875;
END;
ELSE DO;
P_ss_count = 314.875;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 301.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
301.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 516915.5 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 516915.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF 34921783 <= domestic_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_gross < 34921783 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 304.4;
END;
ELSE DO;
P_ss_count = 296.727272727272;
END;
END;
END;
ELSE DO;
P_ss_count = 261.81690140845;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 175.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
175.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 27589 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 27589 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 9938215.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 9938215.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 206 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
206 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.77128852208758 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.77128852208758 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.36492975231531 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.36492975231531 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 223.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
223.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 184267422 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 184267422 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets ) THEN DO;
IF markets < 51.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 51.5 <= markets THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 230.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
230.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 8485830.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 8485830.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 5880069 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 5880069 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 226.333333333333;
END;
ELSE DO;
P_ss_count = 236.157894736842;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 214.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
214.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 47043.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 47043.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 89009547 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 89009547 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 219;
END;
ELSE DO;
P_ss_count = 210.157894736842;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 188.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
188.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 32564.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 32564.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 63440.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 63440.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 180.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
180.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 5643 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 5643 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 5447018.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 5447018.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 177.625;
END;
ELSE DO;
P_ss_count = 183.681818181818;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 197.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
197.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.58884164411802 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.58884164411802 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF ss_std < 0.49226658782807 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.49226658782807 <= ss_std THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 201.625;
END;
ELSE DO;
P_ss_count = 193.5;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 146.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
146.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 6039649.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 6039649.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 13043867.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 13043867.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 160.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
160.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 853412 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 853412 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.72657795709353 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.72657795709353 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 167.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
167.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.73140215606482 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.73140215606482 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_p25 ) THEN DO;
IF 0.25 <= ss_p25 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_p25 < 0.25 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 171.111111111111;
END;
ELSE DO;
P_ss_count = 163.782608695652;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 153.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
153.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 25702.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 25702.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF 5348209.5 <= foreign_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF foreign_gross < 5348209.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 156.761904761904;
END;
ELSE DO;
P_ss_count = 150.608695652173;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 135.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
135.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 4427305 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 4427305 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 12426006.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 12426006.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 141.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
141.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 35687207 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 35687207 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 12954391.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 12954391.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 144.285714285714;
END;
ELSE DO;
P_ss_count = 138.444444444444;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 129.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
129.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 61976 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 61976 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF 106.5 <= runtime THEN DO;
_BRANCH_ = 1;
END;
ELSE IF runtime < 106.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 126.884615384615;
END;
ELSE DO;
P_ss_count = 132.193548387096;
END;
END;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 49.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
49.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 4816 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 4816 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 86.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
86.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 7849 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 7849 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 371487 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 371487 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 104.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
104.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 11548672 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 11548672 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 913923.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 913923.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 113.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
113.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.59648446534577 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.59648446534577 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_p25 ) THEN DO;
IF ss_p25 < 0.875 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.875 <= ss_p25 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 108.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
108.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.80178571428571 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.80178571428571 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.36952401021867 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.36952401021867 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 110.894736842105;
END;
ELSE DO;
P_ss_count = 106.5;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 119.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
119.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF 89.5 <= runtime THEN DO;
_BRANCH_ = 1;
END;
ELSE IF runtime < 89.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.5106457487043 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.5106457487043 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 122.411764705882;
END;
ELSE DO;
P_ss_count = 116.964285714285;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 95.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
95.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_HistDocument ) THEN DO;
_ARBFMT_12 = PUT( genre_HistDocument , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF 1141923 <= foreign_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF foreign_gross < 1141923 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 99.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
99.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 186375.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 186375.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 1766542 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1766542 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 97.375;
END;
ELSE DO;
P_ss_count = 101.863636363636;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 90.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
90.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF runtime < 102.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 102.5 <= runtime THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_DramaTele ) THEN DO;
_ARBFMT_12 = PUT( genre_DramaTele , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 88.2962962962963;
END;
ELSE DO;
P_ss_count = 93.0689655172413;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 65.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
65.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 82808 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 82808 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.43412577549928 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.43412577549928 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 74.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
74.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 1423900 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1423900 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 1816411 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1816411 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 79.28125;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 69.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
69.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_ArthouseInter ) THEN DO;
_ARBFMT_12 = PUT( genre_ArthouseInter , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Comedy ) THEN DO;
_ARBFMT_12 = PUT( genre_Comedy , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 67.2413793103448;
END;
ELSE DO;
P_ss_count = 72.0487804878048;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 56.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
56.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(PG ) THEN DO;
_ARBFMT_12 = PUT( PG , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 5999 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 5999 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 60.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
60.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 156033 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 156033 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 35612 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 35612 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 62.6923076923077;
END;
ELSE DO;
P_ss_count = 58.7777777777777;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 52.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
52.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF runtime < 90.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 90.5 <= runtime THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.755 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.755 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 50.8536585365853;
END;
ELSE DO;
P_ss_count = 54.4651162790697;
END;
END;
END;
END;
END;
ELSE DO;
IF NOT MISSING(tomatometer_count ) AND
23.5 <= tomatometer_count THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 35.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
35.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.42084078711985 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.42084078711985 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_MusicalPerfarts ) THEN DO;
_ARBFMT_12 = PUT( genre_MusicalPerfarts , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 41.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
41.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.89039039039039 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.89039039039039 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF ss_std < 0.31631047847477 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.31631047847477 <= ss_std THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 38.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
38.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF ss_std < 0.47270538495066 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.47270538495066 <= ss_std THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 310015 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 310015 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 39.9722222222222;
END;
ELSE DO;
P_ss_count = 37.0652173913043;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 45.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
45.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF runtime < 109.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 109.5 <= runtime THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_ArthouseInter ) THEN DO;
_ARBFMT_12 = PUT( genre_ArthouseInter , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 47.3636363636363;
END;
ELSE DO;
P_ss_count = 43.5636363636363;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 29.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
29.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 694.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 694.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(NR ) THEN DO;
_ARBFMT_12 = PUT( NR , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 32.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
32.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF runtime < 119 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 119 <= runtime THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.71651785714285 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.71651785714285 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 33.8070175438596;
END;
ELSE DO;
P_ss_count = 30.8181818181818;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 26.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
26.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.88873626373626 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.88873626373626 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.26931337226825 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.26931337226825 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 27.8148148148148;
END;
ELSE DO;
P_ss_count = 25.0714285714285;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 13.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
13.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(G ) THEN DO;
_ARBFMT_12 = PUT( G , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 18.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
18.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 304 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 304 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(NR ) THEN DO;
_ARBFMT_12 = PUT( NR , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 21.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
21.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_ArthouseInter ) THEN DO;
_ARBFMT_12 = PUT( genre_ArthouseInter , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Special_Interest ) THEN DO;
_ARBFMT_12 = PUT( genre_Special_Interest , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 22.4657534246575;
END;
ELSE DO;
P_ss_count = 20.0614035087719;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 15.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
15.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.51295006465553 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.51295006465553 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF 91.5 <= runtime THEN DO;
_BRANCH_ = 1;
END;
ELSE IF runtime < 91.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 16.9150943396226;
END;
ELSE DO;
P_ss_count = 14.4859813084112;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 8.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
8.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.53078438025978 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.53078438025978 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.78888888888888 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.78888888888888 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 10.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
10.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.52463962228091 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.52463962228091 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.86752136752136 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.86752136752136 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 9.49659863945578;
END;
ELSE DO;
P_ss_count = 12;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 6.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
6.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.39310638173654 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.39310638173654 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.84523809523809 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.84523809523809 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 7.5030303030303;
END;
ELSE DO;
P_ss_count = 5.44329896907216;
END;
END;
END;
END;
END;
END;
****************************************************************;
****** END OF DECISION TREE SCORING CODE ******;
****************************************************************;
*;
* ASSIGN VALUE TO: ss_count;
*;
IMP_ss_count = P_SS_COUNT;
END;
