*;
* IMPUTE VARIABLE: ss_count;
*;
format IMP_ss_count BEST12.0;
label IMP_ss_count = 'Imputed ss_count';
IMP_ss_count = ss_count;
if missing(IMP_ss_count) then do;
****************************************************************;
****** DECISION TREE SCORING CODE ******;
****************************************************************;
****** LENGTHS OF NEW CHARACTER VARIABLES ******;
LENGTH _WARN_ $ 4;
****** LABELS FOR NEW VARIABLES ******;
label P_ss_count = 'Predicted: ss_count';
label _WARN_ = 'Warnings';
****** TEMPORARY VARIABLES FOR FORMATTED VALUES ******;
LENGTH _ARBFMT_12 $ 12;
DROP _ARBFMT_12;
_ARBFMT_12 = ' ';
/* Initialize to avoid warning. */
****** ASSIGN OBSERVATION TO NODE ******;
DROP _BRANCH_;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 121.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
121.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 12383.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 12383.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 238.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
238.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 231743239.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 231743239.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 137545156.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 137545156.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 327 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
327 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 182922933.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 182922933.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 102958726 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 102958726 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 393.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
393.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 376441905 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 376441905 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 140096176 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 140096176 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 448.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
448.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 576179353 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 576179353 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 190571546.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 190571546.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 480.428571428571;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 420 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
420 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF 96300149 <= domestic_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_gross < 96300149 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 5863217 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 5863217 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 432.125;
END;
ELSE DO;
P_ss_count = 406.333333333333;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 357.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
357.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 167910000.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 167910000.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 92671584 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 92671584 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 374.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
374.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF 94864660 <= domestic_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_gross < 94864660 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 724863 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 724863 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 384.230769230769;
END;
ELSE DO;
P_ss_count = 364.294117647058;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 343.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
343.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 57798.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 57798.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 4577483.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 4577483.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 351.4375;
END;
ELSE DO;
P_ss_count = 335;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 291 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
291 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 88280750.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 88280750.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 485850716 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 485850716 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 308.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
308.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_DramaTele ) THEN DO;
_ARBFMT_12 = PUT( genre_DramaTele , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 66954.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 66954.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 316.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
316.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets ) THEN DO;
IF 54.5 <= markets THEN DO;
_BRANCH_ = 1;
END;
ELSE IF markets < 54.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF 88494 <= user_rating_count THEN DO;
_BRANCH_ = 1;
END;
ELSE IF user_rating_count < 88494 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 320.1;
END;
ELSE DO;
P_ss_count = 313.363636363636;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 299.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
299.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 164227813.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 164227813.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 137925.5 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 137925.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 302.916666666666;
END;
ELSE DO;
P_ss_count = 295.944444444444;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 258.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
258.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.56129443205893 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.56129443205893 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 6169391.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 6169391.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 247.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
247.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets ) THEN DO;
IF markets < 43 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 43 <= markets THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 69424 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 69424 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 242.846153846153;
END;
ELSE DO;
P_ss_count = 251.838709677419;
END;
END;
ELSE DO;
P_ss_count = 268.47619047619;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 179.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
179.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 58647.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 58647.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 87763018 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 87763018 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 205.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
205.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.73656490550749 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.73656490550749 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.42103622017488 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.42103622017488 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 227.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
227.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF 782481.5 <= foreign_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF foreign_gross < 782481.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 243905.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 243905.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 232.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
232.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 4650000 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 4650000 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets ) THEN DO;
IF markets < 19.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 19.5 <= markets THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 230.071428571428;
END;
ELSE DO;
P_ss_count = 235.117647058823;
END;
END;
ELSE DO;
P_ss_count = 214.5;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 191.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
191.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 62235.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 62235.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.534601938662 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.534601938662 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 184.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
184.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF 19646738.5 <= foreign_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF foreign_gross < 19646738.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 3421940.5 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 3421940.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 187.363636363636;
END;
ELSE DO;
P_ss_count = 181.941176470588;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 198.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
198.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF ss_std < 0.49214764719238 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.49214764719238 <= ss_std THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.59495716411019 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.59495716411019 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 202.566666666666;
END;
ELSE DO;
P_ss_count = 194.88;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 147.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
147.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 6237610.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 6237610.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 7920763.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 7920763.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 135.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
135.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.90035460992907 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.90035460992907 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.25389795667813 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.25389795667813 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 141.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
141.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.61283936651583 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.61283936651583 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.48885035381217 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.48885035381217 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 138.694444444444;
END;
ELSE DO;
P_ss_count = 144.325;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 128.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
128.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 19713.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 19713.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_HistDocument ) THEN DO;
_ARBFMT_12 = PUT( genre_HistDocument , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 125.10909090909;
END;
ELSE DO;
P_ss_count = 131.876712328767;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 160.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
160.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 3385438 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 3385438 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Horror ) THEN DO;
_ARBFMT_12 = PUT( genre_Horror , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 152.022988505747;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 21647.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
21647.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 375242.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 375242.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 143;
END;
ELSE DO;
P_ss_count = 169.434782608695;
END;
END;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 49.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
49.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 4620 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 4620 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 86.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
86.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 8197 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 8197 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 272820.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 272820.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 103.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
103.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 1240429.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1240429.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 8424.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 8424.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 112.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
112.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 8827793.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 8827793.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF 100.5 <= runtime THEN DO;
_BRANCH_ = 1;
END;
ELSE IF runtime < 100.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 117.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
117.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF ss_std < 0.50106530178385 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.50106530178385 <= ss_std THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Action ) THEN DO;
_ARBFMT_12 = PUT( genre_Action , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 119.5;
END;
ELSE DO;
P_ss_count = 115.31914893617;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 107.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
107.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.48545974079129 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.48545974079129 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.60645604395604 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.60645604395604 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 105.315789473684;
END;
ELSE DO;
P_ss_count = 110.086956521739;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 94.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
94.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.88818181818181 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.88818181818181 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.31682693928983 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.31682693928983 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 98.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
98.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 172517 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 172517 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 11850 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 11850 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 96.4444444444444;
END;
ELSE DO;
P_ss_count = 100.837837837837;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 90.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
90.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF ss_std < 0.48861394024953 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.48861394024953 <= ss_std THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 16264411.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 16264411.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 92.5;
END;
ELSE DO;
P_ss_count = 88.5254237288135;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 65.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
65.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 82808 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 82808 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 9137.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 9137.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 75.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
75.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 6766.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 6766.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 1503563 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1503563 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 80.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
80.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 25178 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 25178 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 2327809.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 2327809.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 82.1636363636363;
END;
ELSE DO;
P_ss_count = 78.322033898305;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 70.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
70.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 1181603 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1181603 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 1469716 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1469716 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 72.8805970149253;
END;
ELSE DO;
P_ss_count = 67.9729729729729;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 57.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
57.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(PG ) THEN DO;
_ARBFMT_12 = PUT( PG , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_FamilyKids ) THEN DO;
_ARBFMT_12 = PUT( genre_FamilyKids , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 61.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
61.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_ThrillMysSusp ) THEN DO;
_ARBFMT_12 = PUT( genre_ThrillMysSusp , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 4273 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 4273 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 63.4489795918367;
END;
ELSE DO;
P_ss_count = 59.3898305084745;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 53.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
53.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_ThrillMysSusp ) THEN DO;
_ARBFMT_12 = PUT( genre_ThrillMysSusp , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF 1078.5 <= user_rating_count THEN DO;
_BRANCH_ = 1;
END;
ELSE IF user_rating_count < 1078.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 55.1756756756756;
END;
ELSE DO;
P_ss_count = 51.4683544303797;
END;
END;
END;
END;
END;
ELSE DO;
IF NOT MISSING(tomatometer_count ) AND
22.5 <= tomatometer_count THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 35.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
35.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.26681351958936 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.26681351958936 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.92052631578947 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.92052631578947 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 41.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
41.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.80243902439024 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.80243902439024 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF ss_std < 0.40295320171884 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.40295320171884 <= ss_std THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 38.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
38.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF runtime < 108.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 108.5 <= runtime THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF ss_std < 0.4895709336874 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.4895709336874 <= ss_std THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 39.9428571428571;
END;
ELSE DO;
P_ss_count = 37.0285714285714;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 45.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
45.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF runtime < 92.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 92.5 <= runtime THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(R ) THEN DO;
_ARBFMT_12 = PUT( R , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 47.375;
END;
ELSE DO;
P_ss_count = 43.6274509803921;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 28.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
28.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 1313.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1313.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.84731934731934 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.84731934731934 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 31.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
31.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_FamilyKids ) THEN DO;
_ARBFMT_12 = PUT( genre_FamilyKids , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF user_rating_count < 330.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 330.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 29.991304347826;
END;
ELSE DO;
P_ss_count = 33.4109589041095;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 25.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
25.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.76461538461538 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.76461538461538 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.43277940938886 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.43277940938886 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 26.8955223880597;
END;
ELSE DO;
P_ss_count = 23.9272727272727;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 12.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
12.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(G ) THEN DO;
_ARBFMT_12 = PUT( G , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 17.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
17.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.94281045751634 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.94281045751634 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.23911894271592 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.23911894271592 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 19.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
19.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.51237774588086 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.51237774588086 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.28174603174603 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.28174603174603 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 18.5037037037037;
END;
ELSE DO;
P_ss_count = 20.9252336448598;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 14.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
14.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.51763615057854 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.51763615057854 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_ArthouseInter ) THEN DO;
_ARBFMT_12 = PUT( genre_ArthouseInter , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_ss_count = 13.461139896373;
END;
ELSE DO;
P_ss_count = 15.9889705882352;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 8.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
8.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF 0.11805555555555 <= ss_mean THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_mean < 0.11805555555555 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_FitnessSports ) THEN DO;
_ARBFMT_12 = PUT( genre_FitnessSports , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 10.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
10.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.52463962228091 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.52463962228091 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.8090909090909 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.8090909090909 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 11.4533898305084;
END;
ELSE DO;
P_ss_count = 9.48591549295774;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 6.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
6.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.541122520665 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.541122520665 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.84523809523809 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.84523809523809 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_ss_count = 7.48780487804878;
END;
ELSE DO;
P_ss_count = 5.46428571428571;
END;
END;
END;
END;
END;
END;
****************************************************************;
****** END OF DECISION TREE SCORING CODE ******;
****************************************************************;
*;
* ASSIGN VALUE TO: ss_count;
*;
IMP_ss_count = P_SS_COUNT;
END;
