*;
* IMPUTE VARIABLE: domestic_gross;
*;
format IMP_domestic_gross BEST12.0;
label IMP_domestic_gross = 'Imputed domestic_gross';
IMP_domestic_gross = domestic_gross;
if missing(IMP_domestic_gross) then do;
****************************************************************;
****** DECISION TREE SCORING CODE ******;
****************************************************************;
****** LENGTHS OF NEW CHARACTER VARIABLES ******;
LENGTH _WARN_ $ 4;
****** LABELS FOR NEW VARIABLES ******;
label P_domestic_gross = 'Predicted: domestic_gross';
label _WARN_ = 'Warnings';
****** TEMPORARY VARIABLES FOR FORMATTED VALUES ******;
LENGTH _ARBFMT_12 $ 12;
DROP _ARBFMT_12;
_ARBFMT_12 = ' ';
/* Initialize to avoid warning. */
****** ASSIGN OBSERVATION TO NODE ******;
DROP _BRANCH_;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 431458549.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
431458549.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 327616125.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 327616125.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 55801323 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 55801323 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 1053086479 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
1053086479 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 700722477.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 700722477.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 147267357 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 147267357 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 497513311.6;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 64867979.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
64867979.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 655840098 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 655840098 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 370105126 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 370105126 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 28928919.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
28928919.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 469606267 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 469606267 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF 118.5 <= runtime THEN DO;
_BRANCH_ = 1;
END;
ELSE IF runtime < 118.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_domestic_gross = 118264000.5;
END;
ELSE DO;
P_domestic_gross = 189566976.631578;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 662984906.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
662984906.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 434250000 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 434250000 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 70742152 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 70742152 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_domestic_gross = 246131678.375;
END;
ELSE DO;
P_domestic_gross = 323797585.521739;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 64206743 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
64206743 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 35766112.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 35766112.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 12411898.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 12411898.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 24634798 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
24634798 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 296275822.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 296275822.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 158375303 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 158375303 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 254498315.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
254498315.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 134350000 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 134350000 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 35339879 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 35339879 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 208961013.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
208961013.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 331325858 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 331325858 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 48405104 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 48405104 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_domestic_gross = 167426291.722222;
END;
ELSE DO;
P_domestic_gross = 110756480.95238;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 132593449.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
132593449.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 25118143 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 25118143 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_Horror ) THEN DO;
_ARBFMT_12 = PUT( genre_Horror , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_domestic_gross = 71378579.6153846;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 131451976.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
131451976.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 240844693 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 240844693 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(runtime ) THEN DO;
IF runtime < 135.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 135.5 <= runtime THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 72521487.1666666;
END;
ELSE DO;
P_domestic_gross = 107390454.272727;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(user_rating_count ) AND
user_rating_count < 99053.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(user_rating_count ) AND
99053.5 <= user_rating_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 360595361 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 360595361 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 111177071.666666;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(markets ) AND
markets < 13.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(markets ) AND
13.5 <= markets THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 87173 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 87173 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(genre_ArthouseInter ) THEN DO;
_ARBFMT_12 = PUT( genre_ArthouseInter , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 64202614 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
64202614 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets_missing ) THEN DO;
_ARBFMT_12 = PUT( markets_missing , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 3728 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 3728 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_domestic_gross = 73288337.2;
END;
ELSE DO;
P_domestic_gross = 509991.714285714;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 162418043.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
162418043.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 112808343 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 112808343 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 22869188 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 22869188 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 70556257.2631579;
END;
ELSE DO;
P_domestic_gross = 45819850.637931;
END;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 28116744.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
28116744.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 6301512.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 6301512.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 17831733 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 17831733 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 15401313 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
15401313 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets_missing ) THEN DO;
_ARBFMT_12 = PUT( markets_missing , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 39882055 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 39882055 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 44658762.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
44658762.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 10937926 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 10937926 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 12603338.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 12603338.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( markets_missing , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF 1113824.5 <= foreign_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF foreign_gross < 1113824.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 8349008 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 8349008 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 52165401.6;
END;
ELSE DO;
P_domestic_gross = 40876961.3076923;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 7075418 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
7075418 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets_missing ) THEN DO;
_ARBFMT_12 = PUT( markets_missing , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 144.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 144.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 22604117.75;
END;
ELSE DO;
P_domestic_gross = 32986935.6666666;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 132671 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
132671 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(markets_missing ) THEN DO;
_ARBFMT_12 = PUT( markets_missing , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF 42084245 <= foreign_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF foreign_gross < 42084245 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(ss_count ) AND
ss_count < 88 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(ss_count ) AND
88 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 88 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 88 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF 28106141.5 <= foreign_gross THEN DO;
_BRANCH_ = 1;
END;
ELSE IF foreign_gross < 28106141.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 10335859.8333333;
END;
ELSE DO;
P_domestic_gross = 91770.4615384615;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 50159276.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
50159276.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 8848844.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 8848844.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 21841500 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 21841500 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 29914073.4333333;
END;
ELSE DO;
P_domestic_gross = 17355549.3777777;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 2330896 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
2330896 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 25004096.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 25004096.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 4173377.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
4173377.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 15317086.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 15317086.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 22.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 22.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 15456970.5652173;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 11043128.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
11043128.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 3246547.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 3246547.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 6106755 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 6106755 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_domestic_gross = 6615851.04761904;
END;
ELSE DO;
P_domestic_gross = 11196325.44;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 11968211.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
11968211.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 11862930.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 11862930.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 275.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 275.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(foreign_gross ) AND
foreign_gross < 9241814 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(foreign_gross ) AND
9241814 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(user_rating_count ) THEN DO;
IF 23502.5 <= user_rating_count THEN DO;
_BRANCH_ = 1;
END;
ELSE IF user_rating_count < 23502.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF 93457.5 <= domestic_opening THEN DO;
_BRANCH_ = 1;
END;
ELSE IF domestic_opening < 93457.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_domestic_gross = 14268744.7916666;
END;
ELSE DO;
P_domestic_gross = 2062642.1076923;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 57127.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
57127.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 124.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 124.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 124.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 124.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_domestic_gross = 2134799.72631578;
END;
ELSE DO;
P_domestic_gross = 143510.175394846;
END;
END;
END;
END;
END;
END;
****************************************************************;
****** END OF DECISION TREE SCORING CODE ******;
****************************************************************;
*;
* ASSIGN VALUE TO: domestic_gross;
*;
IMP_domestic_gross = P_DOMESTIC_GROSS;
END;
