*;
* IMPUTE VARIABLE: user_rating_count;
*;
format IMP_user_rating_count BEST12.0;
label IMP_user_rating_count = 'Imputed user_rating_count';
IMP_user_rating_count = user_rating_count;
if missing(IMP_user_rating_count) then do;
****************************************************************;
****** DECISION TREE SCORING CODE ******;
****************************************************************;
****** LENGTHS OF NEW CHARACTER VARIABLES ******;
LENGTH _WARN_ $ 4;
****** LABELS FOR NEW VARIABLES ******;
label P_user_rating_count = 'Predicted: user_rating_count';
label _WARN_ = 'Warnings';
****** TEMPORARY VARIABLES FOR FORMATTED VALUES ******;
LENGTH _ARBFMT_12 $ 12;
DROP _ARBFMT_12;
_ARBFMT_12 = ' ';
/* Initialize to avoid warning. */
****** ASSIGN OBSERVATION TO NODE ******;
DROP _BRANCH_;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 83534399.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
83534399.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 27241980.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 27241980.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 218566203 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 218566203 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
IF NOT MISSING(runtime ) AND
140.5 <= runtime THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 274706186.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
274706186.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 79131250 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 79131250 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 636735337.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 636735337.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_user_rating_count = 375264;
END;
ELSE DO;
P_user_rating_count = 191082.375;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(ss_count ) AND
ss_count < 102.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(ss_count ) AND
102.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 102.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 102.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(NR ) THEN DO;
_ARBFMT_12 = PUT( NR , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_user_rating_count = 3377.75757575757;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 281472843.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
281472843.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 87805861 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 87805861 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 695647428.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 695647428.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_user_rating_count = 154551.684210526;
END;
ELSE DO;
P_user_rating_count = 70342.0476190476;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 16928415 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
16928415 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 5984252 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 5984252 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(total_gross ) THEN DO;
IF total_gross < 29176710 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 29176710 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(ss_count ) AND
ss_count < 71.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(ss_count ) AND
71.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 71.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 71.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(NR ) THEN DO;
_ARBFMT_12 = PUT( NR , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( NR , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF 26.5 <= ss_count THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_count < 26.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF 26.5 <= tomatometer_count THEN DO;
_BRANCH_ = 1;
END;
ELSE IF tomatometer_count < 26.5 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_user_rating_count = 5700.75;
END;
ELSE DO;
P_user_rating_count = 688.452380952381;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 85995661 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
85995661 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 34324807 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 34324807 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 14033080.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 14033080.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_user_rating_count = 47396.4791666666;
END;
ELSE DO;
P_user_rating_count = 27558.6136363636;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 97.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
97.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 97.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 97.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 14610732.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
14610732.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 11615723 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 11615723 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 7931860.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 7931860.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_user_rating_count = 18470.9642857142;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(ss_median ) AND
ss_median < 0.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(ss_median ) AND
0.5 <= ss_median THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.49370853351635 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.49370853351635 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.49753178525477 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.49753178525477 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_user_rating_count = 21661.2;
END;
ELSE DO;
P_user_rating_count = 8274.56476683937;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(ss_count ) AND
ss_count < 41.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(ss_count ) AND
41.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 41.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 41.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(tomatometer_count ) AND
tomatometer_count < 15.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(tomatometer_count ) AND
15.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_count ) THEN DO;
IF ss_count < 15.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 15.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.51327088352783 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.51327088352783 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_gross ) AND
domestic_gross < 12848545.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_gross ) AND
12848545.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 4503853.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 4503853.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_user_rating_count = 11150.6;
END;
ELSE DO;
P_user_rating_count = 1274.57068062827;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(domestic_opening ) AND
domestic_opening < 155702.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(domestic_opening ) AND
155702.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 859831.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 859831.5 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 226340815.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 226340815.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_user_rating_count = 1362.56603773584;
END;
ELSE DO;
P_user_rating_count = 388.969502407704;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(total_gross ) AND
total_gross < 1287161.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(total_gross ) AND
1287161.5 <= total_gross THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(foreign_gross ) THEN DO;
IF foreign_gross < 1173171.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1173171.5 <= foreign_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_gross ) THEN DO;
IF domestic_gross < 807200 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 807200 <= domestic_gross THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( genre_ArthouseInter , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_mean ) THEN DO;
IF ss_mean < 0.85408602150537 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 0.85408602150537 <= ss_mean THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(ss_std ) THEN DO;
IF 0.32540774769982 <= ss_std THEN DO;
_BRANCH_ = 1;
END;
ELSE IF ss_std < 0.32540774769982 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_user_rating_count = 2516.62857142857;
END;
ELSE DO;
P_user_rating_count = 6590.14150943396;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(ss_count ) AND
ss_count < 56.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(ss_count ) AND
56.5 <= ss_count THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(tomatometer_count ) THEN DO;
IF tomatometer_count < 56.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 56.5 <= tomatometer_count THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(domestic_opening ) THEN DO;
IF domestic_opening < 7981.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 7981.5 <= domestic_opening THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_user_rating_count = 1696.173553719;
END;
ELSE DO;
P_user_rating_count = 3362.688;
END;
END;
END;
END;
END;
END;
****************************************************************;
****** END OF DECISION TREE SCORING CODE ******;
****************************************************************;
*;
* ASSIGN VALUE TO: user_rating_count;
*;
IMP_user_rating_count = P_USER_RATING_COUNT;
END;
